apiVersion: v1
kind: Service
metadata:
  name: my-demo-app
  namespace: tips-webinar
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-demo-app
    version: 'e1b7756'
  sessionAffinity: None
  type: LoadBalancer
