apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-demo-app
  template:
    metadata:
      labels:
        name: my-demo-app
        app: my-demo-app
        version: 'e1b7756'
    spec:
      containers:
        - name: my-demo-app
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              memory: "99999Mi"
              # memory: "64Mi"
              cpu: "99999m"
              # cpu: "250m"
            limits:
              memory: "99999999Mi"
              # memory: "128Mi"
              cpu: "9999999m"
              # cpu: "500m"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP