apiVersion: apps/v1
kind: Deployment
metadata:
  name: crasher-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crasher-app
  template:
    metadata:
      labels:
        name: crasher-app
        app: crasher-app
    spec:
      containers:
        - name: crasher-app
          image: poopool/crasher:dev
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 5000
              protocol: TCP
